generatorRepo:
  url: https://github.com/hua-ri/gitops-environment-setup.git
  revision: main

environment:
  file: environments/kind.yaml

project:
  name: platform
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

appSet:
  name: platform-apps
  appsFile: apps/kind/*.yaml
  enabledValue: "true"
  valuesRootDir: values

syncPolicy:
  automated: true
  prune: true
  selfHeal: true

namespace: argo
