auth:
  adminUser: admin
  adminPassword: admin

image:
  registry: docker.m.daocloud.io
  repository: bitnamilegacy/keycloak

keycloakConfigCli:
  image:
    registry: docker.m.daocloud.io
    repository: bitnamilegacy/keycloak-config-cli

postgresql:
  auth:
    password: keycloak
    postgresPassword: postgres
  image:
    registry: docker.m.daocloud.io
    repository: bitnamilegacy/postgresql

proxy: edge

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.local.test
  tls: false
