auth:
  adminUser: admin
  adminPassword: admin

image:
  repository: bitnamilegacy/keycloak

keycloakConfigCli:
  image:
    repository: bitnamilegacy/keycloak-config-cli

postgresql:
  image:
    repository: bitnamilegacy/postgresql

proxy: edge

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.local.test
  tls: false
